/*
 Amanda New
 01/19/2025
 CSD402-A311
 M3: Programming Assignment
 Number Pyramid

 * This source file was generated by the Gradle 'init' task
 
 Package for organization within code file
 */
package module;

/*Class */
public class pyramid {

    /*Main method */
    public static void main(String[] args) {

        // Define number of rows 
        int rows = 7; 

        // Insert leading spaces
        for (int i = 0; i < rows; i++) {
            int spaces = rows - i - 1;
            for (int j = 0; j < spaces; j++) {
                System.out.print("   "); 
            }

            // Calculate and print the numbers in forward order; formatting with width 3
            int num = 1;
            for (int j = 0; j <= i; j++) {
                System.out.printf("%3d", num); 
                num *= 2; 
            }

            // Calculate and print the numbers in reverse order; formatting with width 3
            num /= 2; 
            for (int j = i - 1; j >= 0; j--) {
                num /= 2; 
                System.out.printf("%3d", num);
            }

            // Insert spaces after last number
            for(int j = 0; j < spaces; j++) {
                System.out.print("   ");
            }

            // Insert @ symbol to be aligned after ending spaces
            System.out.print("   @");

            //Move to the next line to print the next statement
            System.out.println();

        }
    }
}