/*
Amanda New
02/02/2025
CSD402-A311
M6: Programming Assignment
 * This source file was generated by the Gradle 'init' task
 
Package for organization within code file
*/
package module;

public class Fan {
    //constants: speed
    public static final int STOPPED = 0;
    public static final int SLOW = 1;
    public static final int MEDIUM = 2;
    public static final int FAST = 3;

    //private fields
    private int speed;
    private boolean on;
    private double radius;
    private String color;

    //default values
    public Fan() {
        this.speed = STOPPED;
        this.on = false;
        this.radius = 6.0;
        this.color = "white";
    }

    //argument contructor for custom values
    public Fan(int speed, boolean on, double radius, String color) {
        this.speed = speed;
        this.on = on; 
        this.radius = radius;
        this.color = color;
    }

    //getter and setter methods for speed, state/boolean, radius, and color
    public int getSpeed() {
        return speed;
    }

    public void setSpeed(int speed) {
        this.speed = speed;
    }

    public boolean isOn() {
        return on;
    }

    public void setOn(boolean on) {
        this.on = on;
    }

    public double getRadius() {
        return radius;
    }

    public void setRadius(double radius) {
        this.radius = radius;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    //method to describe fan's state
    public String toString() {
        String state = (on) ? "on" : "off";
        String speedString = "";

        switch (speed) {
            case STOPPED:
                speedString = "STOPPED";
                break;
            case SLOW:
                speedString = "SLOW";
                break;
            case MEDIUM:
                speedString = "MEDIUM";
                break;
            case FAST:
                speedString = "FAST";
                break;
            
        }
        //description return
        return "Fan is " + state + "\nSpeed: " + speedString + "\nRadius: " + radius + " inches\nColor: " + color;

    }
    //main method for creating two instances of Fan class
    public static void main(String[] args) {
        //default constructor
        Fan fan1 = new Fan();
        System.out.println("Default Constructor Fan:");
        System.out.println(fan1);
        System.out.println();

        //argument constructor
        Fan fan2 = new Fan(Fan.MEDIUM, true, 10.0, "blue");
        System.out.println("Argument Constructor Fan:");
        System.out.println(fan2);
    }
}
