/*
Amanda New
02/23/2025
CSD402-A311
M10: Division

 * This source file was generated by the Gradle 'init' task

 Package for organization within code file
*/
package module;

public abstract class Division {
    private String divisionName;
    private String accountNumber;

    // initialize division name and account number constructor
    public Division(String divisionName, String accountNumber) {
        this.divisionName = divisionName;
        this.accountNumber = accountNumber;
    }

    //abstract method for display
    public abstract void display();

    //getters
    public String getDivisionName() {
        return divisionName;
    }

    public String getAccountNumber() {
        return accountNumber;
    }
}
