/*
Amanda New
02/23/2025
CSD402-A311
M10: UseDivision

 * This source file was generated by the Gradle 'init' task

 Package for organization within code file
*/

package module; 

public class UseDivision {
    //main method
    public static void main(String[] args) {

        //two international instances
        InternationalDivision international1 = new InternationalDivision(
            "South America", "90001234", "Brazil", "Portuguese");
        InternationalDivision international2 = new InternationalDivision(
            "Asia", "90005678", "South Korea", "Korean");

        //two domestic instances
        DomesticDivision domestic1 = new DomesticDivision(
            "East", "10001234", "Georgia");
        DomesticDivision domestic2 = new DomesticDivision(
            "West", "10005678", "Nevada");

        //display information for both
        international1.display();
        international2.display();
        domestic1.display();
        domestic2.display();
    }
}