/*
Amanda New
02/02/2025
CSD402-A311
M5: Programming Assignment

 * This source file was generated by the Gradle 'init' task
 
  Package for organization within code file
 */
package module;

//class
public class arrayLocator {
    //method for largest double element
    public static int[] locateLargest(double[][] arrayParam) {
        //initialize new array to store largest elements and to assume first spot in index is the largest
        int[] location = new int[2];
        double largest = arrayParam[0][0];
        location[0] = 0; //row index
        location[1] = 0; //column index

        //work through array to find largest element
        for (int i = 0; i < arrayParam.length; i++) {
            for (int j=0; j < arrayParam[i].length; j++) {
                if (arrayParam[i][j] > largest) {
                    largest = arrayParam[i][j];
                    location[0] = i; //update row
                    location[1] = j; //update column
                }
            }
        }
        return location;
    }
    
    //method for largest int element
    public static int[] locateLargest(int[][] arrayParam) {
        //initialize new array to store largest elements and to assume first spot in index is the largest
        int [] location = new int[2];
        int largest = arrayParam[0][0];
        location[0] = 0;
        location[1] = 0;

        for (int i = 0; i < arrayParam.length; i++) {
            for (int j=0; j < arrayParam[i].length; j++) {
                if (arrayParam[i][j] > largest) {
                    largest = arrayParam[i][j];
                    location[0] = i;
                    location[1] = j;
                }
            }
        }
        return location;
    }

    //method for smallest double element
    public static int[] locateSmallest(double[][] arrayParam) {
        //initialize new array to store smallest elements and to assume first spot in index is the smallest
        int[] location = new int[2];
        double smallest = arrayParam[0][0];
        location[0] = 0;
        location[1] = 0;

        //work through array to find smallest element
        for (int i = 0; i < arrayParam.length; i++) {
            for (int j = 0; j < arrayParam[i].length; j++) {
                if (arrayParam[i][j] < smallest) {
                    smallest = arrayParam[i][j];
                    location[0] = i;
                    location[1] = j;
                }
            }
        }
        return location;
    }

    //method for smallest double element
    public static int[] locateSmallest(int[][] arrayParam) {
        //initialize new array to store smallest elements and to assume first spot in index is the smallest
        int[] location = new int[2];
        int smallest = arrayParam[0][0];
        location[0] = 0;
        location[1] = 0;

        for (int i=0; i < arrayParam.length; i++) {
            for (int j = 0; j < arrayParam[i].length; j++) {
                if (arrayParam[i][j] < smallest) {
                    smallest = arrayParam[i][j];
                    location[0] = i;
                    location[1] = j;
                }
            }
        }
        return location;
    }
    
    //method to define arrays and print array locations
    public static void main(String[] args) {
        //define double array
        double[][] doubleArray = {
                {7.8, 8.7, 8.9},
                {4.5, 5.4, 5.6},
                {1.2, 2.1, 2.3}

        };

        //define int array
        int[][] intArray = {
            {1, 2, 3},
            {4, 8, 9}, 
            {5, 6, 7}
    };
        //print largest element locations
        int[] largestDouble = locateLargest(doubleArray);
        System.out.println("Largest double element located at: [" + largestDouble[0] + ", " + largestDouble[1] + "]");

        int[] largestInt = locateLargest(intArray);
        System.out.println("Largest int element located at: [" + largestInt[0] + ", " + largestInt[1] + "]");


        //print smallest element locations
        int[] smallestDouble = locateSmallest(doubleArray);
        System.out.println("Smallest double located element at: [" + smallestDouble[0] + ", " + smallestDouble[1] + "]");

        int[] smallestInt = locateSmallest(intArray);
        System.out.println("Smallest int located element at: [" + smallestInt[0] + ", " + smallestInt[1] + "]");
 
    } 
}
