/*
Amanda New
02/16/2025
CSD402-A311
M9: Program 1

 * This source file was generated by the Gradle 'init' task
 
Package for organization within code file
*/
package module;

import java.util.ArrayList;
import java.util.Scanner;

public class NewArray {

    public static void main(String[] args) {
        //ArrayList with 10 elements
        ArrayList<String> stringsList = new ArrayList<>();
        stringsList.add("Squirtle");
        stringsList.add("Totodile");
        stringsList.add("Mudkip");
        stringsList.add("Piplup");
        stringsList.add("Oshawott");
        stringsList.add("Froakie");
        stringsList.add("Popplio");
        stringsList.add("Sobble");
        stringsList.add("Quaxly");
        stringsList.add("Pikachu");

        //"for-each" loop to print ArrayList
        System.out.println("All Pokemon - ArrayList Elements:");
        for (String pokemon : stringsList) {
            System.out.println(pokemon);
        }
        
        //ask user which element they want to see again
        Scanner scanner = new Scanner(System.in);
        System.out.print("\nWhich Pokemon do you want to see again? (Enter index): ");
        String userInput = scanner.nextLine();

        try {
            //Auto-Unboxing
            int index = Integer.parseInt(userInput);
            //print out element at given index
            System.out.println("The Pokemon you chose at index " + index + " is " + stringsList.get(index) + "!");

        //out of bounds
        } catch (IndexOutOfBoundsException e) {
            System.out.println("Exception: Out of Bounds");
        
        //invalid input
        } catch (NumberFormatException e) {
            System.out.println("Invalid number, choose 0-9 and please try again!");
        }

        scanner.close();
    
    }
}
