/*
Amanda New
02/09/2025
CSD402-A311
M7: Programming Assignment

 * This source file was generated by the Gradle 'init' task
 
Package for organization within code file
*/
package module;

import java.util.ArrayList;
import java.util.List;

public class FanFan {
    //constants: speed
    public static final int STOPPED = 0;
    public static final int SLOW = 1;
    public static final int MEDIUM = 2;
    public static final int FAST = 3;

    //private fields
    private int speed;
    private boolean on;
    private double radius;
    private String color;

    //default values
    public FanFan() {
        this.speed = STOPPED;
        this.on = false;
        this.radius = 6.0;
        this.color = "white";
    }

    //argument contructor for custom values
    public FanFan(int speed, boolean on, double radius, String color) {
        this.speed = speed;
        this.on = on; 
        this.radius = radius;
        this.color = color;
    }

    //getter and setter methods for speed, state/boolean, radius, and color
    public int getSpeed() {
        return speed;
    }

    public void setSpeed(int speed) {
        this.speed = speed;
    }

    public boolean isOn() {
        return on;
    }

    public void setOn(boolean on) {
        this.on = on;
    }

    public double getRadius() {
        return radius;
    }

    public void setRadius(double radius) {
        this.radius = radius;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    //method to describe fan's state
    public String toString() {
        String state = (on) ? "on" : "off";
        String speedString = "";

        switch (speed) {
            case STOPPED:
                speedString = "STOPPED";
                break;
            case SLOW:
                speedString = "SLOW";
                break;
            case MEDIUM:
                speedString = "MEDIUM";
                break;
            case FAST:
                speedString = "FAST";
                break;
            
        }
        //description return
        return "Fan is " + state + "\nSpeed: " + speedString + "\nRadius: " + radius + " inches\nColor: " + color;

    }

    //single fan method without toString()
    public static void displayFanDetails(FanFan fan) {
        System.out.println("Fan is " + (fan.isOn() ? "on" : "off"));
        System.out.println("Speed: " + (fan.getSpeed() == STOPPED ? "STOPPED" : fan.getSpeed() == SLOW ? "SLOW" : fan.getSpeed() == MEDIUM ? "MEDIUM" : "FAST"));
        System.out.println("Radius: " + fan.getRadius() + " inches");
        System.out.println("Color: " + fan.getColor());
        System.out.println();
    }

    //fan collection without toString()
    public static void displayAllFans(List<FanFan> fans) {
        for (FanFan fan : fans) {
            displayFanDetails(fan);
        }
    }

    //main method replaced - now testing and displaying fans
    public static void main(String[] args) {
        List<FanFan> fanCollection = new ArrayList<>();

        FanFan fan1 = new FanFan();
        fanCollection.add(fan1);

        FanFan fan2 = new FanFan(FanFan.MEDIUM, true, 10.0, "blue");
        fanCollection.add(fan2);

        FanFan fan3 = new FanFan (FanFan.FAST, true, 8.0, "red");
        fanCollection.add(fan3);

        FanFan fan4 = new FanFan (FanFan.SLOW, false, 5.0, "green");
        fanCollection.add(fan4);

        System.out.println("Displaying all fans:");
        System.out.println();
        displayAllFans(fanCollection);
    }
}