/*
Amanda New
01/26/2025
CSD402-A311
M4: Programming Assignment
Arrays

 * This source file was generated by the Gradle 'init' task
 
 Package for organization within code file
 */
package module;


/*Class */
public class avgArray {
    /* Calculate average of short array */
    public static short average(short [] array) {
        int sum = 0;
        for (short num : array) {
            sum += num; 
        }
        return (short)(sum / array.length); 
    }
    /* Calculate average of int array */
    public static int average(int [] array) {
        int sum = 0;
        for (int num : array) {
            sum += num;
        }
        return sum / array.length;
    }
    /* Calculate average of long array */
    public static long average(long [] array) {
        long sum = 0;
        for (long num : array) {
            sum += num;
        }
        return sum / array.length;
    }
    /* Calculate average of double array */
    public static double average(double [] array) {

        double sum = 0;
        for (double num : array) {
            sum += num;
        }
        return sum / array.length;
    }
    /* main method */
    public static void main (String[] args) {
        /* Define array values */
        short[] shortArray = {3, 4, 6, 13, 16, 26};
        int [] intArray = {4000, 8000, 10000, 12000, 15000};
        long [] longArray = {280, 281, 282, 742, 743, 868, 869};
        double [] doubleArray = {1.2, 2.1, 1.3, 6.6};

        /*Print Arrays and Averages */

        System.out.println("Short Array Example: ");
        /* Print arrays to where it's readable*/
        for (short value : shortArray) {
            System.out.print(value + " ");
        }
        System.out.println("\nAverage: " + average(shortArray));

        System.out.println("\nInt Array Example: ");
        for (int value : intArray) {
            System.out.print(value + " ");
        }
        System.out.println("\nAverage: " + average(intArray));

        System.out.println("\nLong Array Example: ");
        for (long value : longArray) {
            System.out.print(value + " ");
        }
        System.out.println("\nAverage: " + average(longArray));

        System.out.println("\nDouble Array Example: ");
        for (double value : doubleArray) {
            System.out.print(value + " ");
        }
        System.out.println("\nAverage : " + average(doubleArray));

    }

}
